# melpazoid <https://github.com/riscy/melpazoid> build checks.

# If your package is on GitHub, enable melpazoid's checks by copying this file
# to .github/workflows/melpazoid.yml and modifying RECIPE and EXIST_OK below.

name: melpazoid
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with: { python-version: 3.6 }
    - uses: purcell/setup-emacs@master
      with:
        version: 27.1
    - uses: ./
      with:
        recipe: '(melpazoid :fetcher github :repo "riscy/melpazoid" :files ("melpazoid/melpazoid.el"))'
